function [ projectDirectoriesCellStr ] = getProjectDirectoriesForMatlabPath( )

% Copyright 2021, The MathWorks, Inc.

import tirepressuremonitordemo.utilities.*;

projectRootDirectoryAbsolutePath = ...
    getProjectRootDirectoryAbsolutePath( );

projectDirectoriesCellStr = ...
    { ...
    projectRootDirectoryAbsolutePath, ...
    fullfile( projectRootDirectoryAbsolutePath,'bus_constructors'), ...
    ...
    fullfile( projectRootDirectoryAbsolutePath,'data_dictionaries'), ...
    ...
    fullfile( projectRootDirectoryAbsolutePath,'enumerations'), ...
    ...
    fullfile( projectRootDirectoryAbsolutePath,'models'), ...
    fullfile( projectRootDirectoryAbsolutePath,'models','controller'), ...
    fullfile( projectRootDirectoryAbsolutePath,'models','controller','data_dictionaries'), ...
    fullfile( projectRootDirectoryAbsolutePath,'models','controller','wrappers'), ...
    fullfile( projectRootDirectoryAbsolutePath,'models','controller','target_specific_code'), ...
    fullfile( projectRootDirectoryAbsolutePath,'models','controller','target_specific_code','data_dictionaries'), ...
    ...
    fullfile( projectRootDirectoryAbsolutePath,'models','sensor'), ...
    fullfile( projectRootDirectoryAbsolutePath,'models','sensor','data_dictionaries'), ...
    fullfile( projectRootDirectoryAbsolutePath,'models','sensor','wrappers'), ...
    fullfile( projectRootDirectoryAbsolutePath,'models','sensor','target_specific_code'), ...
    fullfile( projectRootDirectoryAbsolutePath,'models','sensor','target_specific_code','data_dictionaries'), ...
    ...
    fullfile( projectRootDirectoryAbsolutePath,'models','system_level'), ...
    fullfile( projectRootDirectoryAbsolutePath,'models','system_level','data_dictionaries'), ...
    fullfile( projectRootDirectoryAbsolutePath,'models','system_level','simulation_data_inspector_views'), ...
    };

return;

end
