struct ShapeType {
    string<128> color; //@key
    //@ID 0
    long x;    //@ID 1
    long y;    //@ID 2
    long shapesize;    //@ID 3
};
//@Extensibility EXTENSIBLE_EXTENSIBILITY

enum ShapeFillKind {
    @default_literal
    SOLID_FILL = 0,
    TRANSPARENT_FILL = 1,
    HORIZONTAL_HATCH_FILL = 2,
    VERTICAL_HATCH_FILL = 3
};
//@Extensibility EXTENSIBLE_EXTENSIBILITY

struct ShapeTypeExtended : ShapeType {
    ShapeFillKind fillKind;    //@ID 4
    float angle;    //@ID 5
};
//@Extensibility EXTENSIBLE_EXTENSIBILITY