@startuml
class Order {
    dateReceived : Date[0..1]
    isPrepaid:boolean[1]
    nnumber: String[1]
    price : Money 
    dispatch()
    close()
}

class Customer {
    name [1]
    address [0..1]
    getCreditRating():String
}

class OrderLine {
    quantity : Integer 
    price : Money 

}

Order  "*" -> "1" Customer
Order "1" --> "* {ordered}" OrderLine : > lineItems
OrderLine --> Product
Customer <|-- CorporateCustomer
Customer <|-- PersonalCustomer
CorporateCustomer "*" --> "0..1" Employee : > salesRep



@enduml