#ifndef PORTABLE_WORDSIZES
#ifdef __MW_TARGET_USE_HARDWARE_RESOURCES_H__
#ifndef __MW_TARGET_HARDWARE_RESOURCES_H__
#define __MW_TARGET_HARDWARE_RESOURCES_H__


#define MW_USECODERTARGET 1
#define MW_TARGETHARDWARE QNX-x86
#define MW_RTOS QNX-x86
#define MW_RTOSBASERATETASKPRIORITY 40
#define MW_DETECTTASKOVERRUNS 0.000000
#define MW_SCHEDULER_INTERRUPT_SOURCE 0
#define MW_RUNTIME_BUILDACTION 1
#define MW_SCHEDULEROPTIONS_SCHED_ALGO 0
#define MW_SCHEDULEROPTIONS_CLOCK_TYPE 1
#define MW_EXTMODEOPTIONS_PORTNUM 4000
#define MW_DATAVERSION 2016.02
#define MW_MULTI_TASKING_MODE 1

#endif /* __MW_TARGET_HARDWARE_RESOURCES_H__ */

#endif

#endif
